Repository kids-first/kf-api-release-coordinator, pull requests merged in 2019-10, with the labels that each got.

#219 ✨ Graphql release mutations
  coordinator/graphql/releases.py
  coordinator/graphql/schema.py
  tests/graphql/releases/test_cancel_release.py
  tests/graphql/releases/test_create_release.py
  tests/graphql/releases/test_publish_release.py
Labels: feature

#220 ✨ Add release subquery to studies
  coordinator/graphql/studies.py
  tests/graphql/studies/test_study_queries.py
Labels: feature

#223 ✨ Add Task Service mutations
  coordinator/graphql/schema.py
  coordinator/graphql/task_services.py
  tests/graphql/task_services/test_create_task_service.py
  tests/graphql/task_services/test_update_task_service.py
Labels: feature

#224 🔊 Create events for requests errors
  coordinator/tasks.py
Labels: feature

#226 ✨ Add syncStudies mutation
  coordinator/api/views/studies.py
  coordinator/dataservice.py
  coordinator/graphql/schema.py
  coordinator/graphql/studies.py
  tests/graphql/studies/test_study_sync.py
  tests/test_studies.py
Labels: feature

#227 ♻️ Only validate url when changed
  coordinator/graphql/task_services.py
Labels: refactor

#228 🐛 Fix auth headers
  coordinator/middleware.py
  coordinator/settings/production.py
Labels: bug

#229 👷 Changing Jenkins to Production library
  Jenkinsfile
Labels: devops

#230 ✨ User profiles
  coordinator/api/factories/user.py
  coordinator/api/migrations/0012_extend_event_message.py
  coordinator/api/models/event.py
  coordinator/api/views/release.py
  coordinator/api/views/release_note.py
  coordinator/api/views/task.py
  coordinator/api/views/task_service.py
  coordinator/authentication.py
  coordinator/graphql/events.py
  coordinator/graphql/release_notes.py
  coordinator/graphql/releases.py
  coordinator/graphql/schema.py
  coordinator/graphql/studies.py
  coordinator/graphql/task_services.py
  coordinator/graphql/tasks.py
  coordinator/graphql/users.py
  coordinator/middleware.py
  coordinator/migrations/0001_initial.py
  coordinator/migrations/__init__.py
  coordinator/models.py
  coordinator/permissions.py
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
  coordinator/tasks.py
  pytest.ini
  tests/conftest.py
  tests/graphql/tasks/test_task_queries.py
  tests/graphql/users/test_user_queries.py
  tests/test_tasks.py
Labels: feature

#231 🐛 Fix task events
  coordinator/authentication.py
  coordinator/tasks.py
Labels: bug

#233 🐛 Fix error message
  coordinator/tasks.py
Labels: bug

#234 🔊 Add task logging
  coordinator/api/views/task.py
  coordinator/authentication.py
  coordinator/settings/production.py
  coordinator/tasks.py
Labels: devops, refactor

#236 🔧 Allow cookies in requests
  coordinator/settings/production.py
Labels: feature

#235 🖼 Update readme
  README.md
  docs/_static/images/coordinator_flow.svg
  docs/_static/images/flow.png
  docs/_static/images/notes.svg
  docs/_static/images/release_coordinator.svg
  docs/_static/images/services.svg
  docs/_static/images/versioning.svg
Labels: documentation
