Repository kids-first/kf-api-release-coordinator, pull requests merged in 2019-03, with the labels that each got.

#137 🐳 Add dev stage to docker
  Dockerfile
  docker-compose.yml
Labels: devops

#140 ♻️ App pytest.ini for quick access pytest
  .circleci/config.yml
  pytest.ini
Labels: refactor

#138 ⬆️ Bump Django version
  coordinator/api/serializers/release.py
  requirements.txt
  tests/conftest.py
  tests/test_auth.py
  tests/test_end_to_end.py
  tests/test_notes.py
  tests/test_tasks.py
Labels: refactor

#145 🔥 Remove setup.cfg
  setup.cfg
Labels: refactor

#144 🔧 Improve docker-compose for development
  bin/dev_entrypoint.sh
  bin/dev_worker.sh
  docker-compose.yml
Labels: devops, refactor

#150 🙈 Ignore ci files in jenkins
  pytest.ini
Labels: bug, devops

#148 🐛 Update testing with correct apps
  coordinator/settings/testing.py
Labels: bug

#147 🐛 Fix static paths
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
Labels: bug

#151 ✨ Store ego public key
  coordinator/authentication.py
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
  tests/admin_token.txt
  tests/conftest.py
  tests/dev_token.txt
  tests/failures/test_fail_initialize.py
  tests/failures/test_fail_run.py
  tests/keys/other_private_key.pem
  tests/keys/private_key.pem
  tests/keys/public_key.pem
  tests/test_auth.py
  tests/test_end_to_end.py
  tests/test_notes.py
  tests/test_tasks.py
  tests/user_token.txt
Labels: feature, refactor

#152 ♻️ Load secrets directly from vault
  Dockerfile
  bin/entrypoint.sh
  bin/load_vault.sh
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
  requirements.txt
Labels: devops, refactor

#154 🔥 Replace pep8 with codestyle
  dev-requirements.txt
  pytest.ini
Labels: refactor

#155 ♻️ Store Ego service token for coordinator in cache
  coordinator/api/models/task.py
  coordinator/api/models/taskservice.py
  coordinator/authentication.py
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
  coordinator/tasks.py
  tests/ego_token.json
  tests/test_jwtstore.py
Labels: refactor

#156 🐛 Allow releases to re-enter cancelling state
  coordinator/api/models/release.py
  coordinator/api/models/task.py
  tests/failures/test_fail_cancel_release.py
Labels: bug

#157 🐛 Fix EGO settings
  coordinator/settings/development.py
  coordinator/settings/production.py
Labels: bug

#158 🐛 Fix typo in secret path
  bin/load_vault.sh
Labels: bug

#159 ♻️ Read secrets as raw strings
  bin/load_vault.sh
Labels: bug

#160 ✨ Add auth0 token validation
  coordinator/api/views/release.py
  coordinator/api/views/task_service.py
  coordinator/authentication.py
  coordinator/permissions.py
  coordinator/settings/development.py
  coordinator/settings/production.py
  coordinator/settings/testing.py
  tests/test_auth.py
Labels: feature

#162 🔧 Add netlify to CORS whitelist
  coordinator/settings/production.py
Labels: feature

#164 ✅ Add test for unauthed user cannot access study releases
  tests/test_auth.py
Labels: refactor

#165 ♻️ Refactor for getting db host from environment
  bin/dev_entrypoint.sh
Labels: refactor
